In [40]:
import numpy as np
import pandas as pd
import glob
from tqdm.auto import tqdm

# MSE imports
import kepler_sieve
from ztf_data import load_ztf_det_all

In [4]:
# Plotting
import matplotlib.pyplot as plt
import matplotlib as mpl

In [5]:
# Set plot style variables
mpl.rcParams['figure.figsize'] = [16.0, 10.0]
mpl.rcParams['font.size'] = 16

In [6]:
ztf, mjd_unq = load_ztf_det_all()

In [7]:
ztf

,ObjectID,CandidateID,TimeStampID,mjd,ra,dec,ux,uy,uz,mag_app,asteroid_prob
0,b'ZTF18acebhfp',676397301515010013,14490,58430.397303,41.357345,58.879488,0.387942,0.653853,0.649598,18.946699,0.865682
1,b'ZTF18abodmwk',596403415715010014,5831,58350.403414,30.969721,65.305308,0.358224,0.558644,0.748059,19.010401,0.855504
2,b'ZTF18abodmwk',626428345715010011,10614,58380.428345,30.969705,65.305294,0.358224,0.558644,0.748059,18.935900,0.855504
3,b'ZTF18abodmwk',630507595715015045,11250,58384.507593,30.969940,65.305305,0.358223,0.558645,0.748059,19.260401,0.855504
4,b'ZTF18abodmwk',618384965715010022,9040,58372.384965,30.969643,65.305179,0.358226,0.558644,0.748058,19.220200,0.855504
...,...,...,...,...,...,...,...,...,...,...,...
5697957,b'ZTF20aareruw',1151532523515015015,97109,58905.532523,253.007910,55.485537,-0.165587,-0.169403,0.971537,19.192400,0.608023
5697958,b'ZTF20aarerwx',1151533002615015009,97110,58905.533009,232.886408,53.509617,-0.358833,-0.115301,0.926253,19.687099,0.559474
5697959,b'ZTF20aarerww',1151533002115010003,97110,58905.533009,236.167899,54.618457,-0.322375,-0.116973,0.939357,19.957001,0.392662
5697960,b'ZTF20aarervr',1151526063515015015,97098,58905.526065,286.235286,33.876902,0.232120,-0.509626,0.828494,19.049299,0.517241
5697961,b'ZTF18aajqsjs',1151533002315015001,97110,58905.533009,237.382168,53.766297,-0.318612,-0.135924,0.938089,18.847700,0.992615

In [24]:
ztf.loc[979457:979457]

,ObjectID,CandidateID,TimeStampID,mjd,ra,dec,ux,uy,uz,mag_app,asteroid_prob
979457,b'ZTF19abqgyuh',959491202915015011,46143,58713.491204,94.970998,25.528057,-0.078192,0.996222,0.037798,19.0979,1.0

In [8]:
hash_id = 4136886054897592978

In [9]:
file_path = f'../data/ztf_elt/ztf_elt_{hash_id}.h5'

In [25]:
ztf_elt = pd.read_hdf(file_path)

In [26]:
ztf_elt

,ztf_id,element_id,ObjectID,CandidateID,TimeStampID,mjd,ra,dec,ux,uy,...,elt_ux,elt_uy,elt_uz,elt_r,s,s_sec,z,v,is_hit,is_match
0,979457,41536,b'ZTF19abqgyuh',959491202915015011,4243,58713.491204,94.970998,25.528057,-0.078192,0.996222,...,-0.086246,0.994819,0.053826,2.557208,0.017992,3711.187869,0.999838,0.265701,False,False
1,980136,41536,b'ZTF19abqgyrl',959491203015015000,4243,58713.491204,95.547195,24.976217,-0.087626,0.995745,...,-0.086246,0.994819,0.053826,2.557208,0.025370,5233.125033,0.999678,0.528297,False,False
2,980267,41536,b'ZTF19abqgyvl',959491204515015007,4243,58713.491204,95.304729,27.190976,-0.082236,0.994362,...,-0.086246,0.994819,0.053826,2.557208,0.013729,2831.829235,0.999906,0.154706,False,False
3,980711,41536,b'ZTF19abqgyry',959490301615015004,4241,58713.490301,94.917750,25.555531,-0.077339,0.996271,...,-0.086239,0.994819,0.053826,2.557215,0.017999,3712.651258,0.999838,0.265911,False,False
4,980750,41536,b'ZTF19abqgyry',959491202915015010,4243,58713.491204,94.918132,25.555546,-0.077345,0.996270,...,-0.086246,0.994819,0.053826,2.557208,0.017999,3712.695311,0.999838,0.265917,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
484054,3872982,41599,b'ZTF19adakwkp',1083089322515015083,25517,58837.089329,321.667207,-10.155908,0.772131,-0.630271,...,0.761951,-0.643128,0.076270,3.191495,0.017087,3524.552736,0.999854,0.239650,False,False
484055,3873051,41599,b'ZTF19adakvwh',1083089322615015026,25517,58837.089329,321.430310,-11.448652,0.766294,-0.639592,...,0.761951,-0.643128,0.076270,3.191495,0.016307,3363.591011,0.999867,0.218261,False,False
484056,3873073,41599,b'ZTF19adakvwb',1083089322415015006,25517,58837.089329,322.401108,-10.375126,0.779347,-0.622267,...,0.761951,-0.643128,0.076270,3.191495,0.027304,5632.051718,0.999627,0.611907,False,False
484057,3873086,41599,b'ZTF19adakwtb',1083089322715015063,25517,58837.089329,322.730497,-11.238179,0.780537,-0.622464,...,0.761951,-0.643128,0.076270,3.191495,0.033563,6923.245307,0.999437,0.924608,False,False
484058,3901617,41599,b'ZTF19adbkcuw',1086095282215015019,26066,58840.095289,323.123836,-11.600120,0.783596,-0.619309,...,0.774218,-0.628413,0.075386,3.217623,0.029143,6011.429465,0.999575,0.697114,False,False

In [27]:
ztf_elt.columns

Index(['ztf_id', 'element_id', 'ObjectID', 'CandidateID', 'TimeStampID', 'mjd',
       'ra', 'dec', 'ux', 'uy', 'uz', 'nearest_ast_num', 'nearest_ast_dist',
       'ast_ra', 'ast_dec', 'ast_ux', 'ast_uy', 'ast_uz', 'qx', 'qy', 'qz',
       'vx', 'vy', 'vz', 'elt_ux', 'elt_uy', 'elt_uz', 'elt_r', 's', 's_sec',
       'z', 'v', 'is_hit', 'is_match'],
      dtype='object')

In [28]:
loc = ztf_elt.columns.get_loc('uz')+1

In [29]:
mag_app = ztf.mag_app.loc[ztf_elt.ztf_id].values

In [36]:
if 'mag_app' not in ztf_elt.columns:
    ztf_elt.insert(loc=loc, column='mag_app', value=mag_app)
else:
    ztf_elt['mag_app'] = mag_app

In [33]:
cols = ['ztf_id', 'element_id', 'mjd', 'ra', 'dec', 'ux', 'uy', 'uz', 'mag_app']
ztf_elt[cols]

,ztf_id,element_id,mjd,ra,dec,ux,uy,uz,mag_app
0,979457,41536,58713.491204,94.970998,25.528057,-0.078192,0.996222,0.037798,19.097900
1,980136,41536,58713.491204,95.547195,24.976217,-0.087626,0.995745,0.028510,18.854000
2,980267,41536,58713.491204,95.304729,27.190976,-0.082236,0.994362,0.066948,14.790400
3,980711,41536,58713.490301,94.917750,25.555531,-0.077339,0.996271,0.038248,18.589001
4,980750,41536,58713.491204,94.918132,25.555546,-0.077345,0.996270,0.038249,18.569201
...,...,...,...,...,...,...,...,...,...
484054,3872982,41599,58837.089329,321.667207,-10.155908,0.772131,-0.630271,0.081070,19.192600
484055,3873051,41599,58837.089329,321.430310,-11.448652,0.766294,-0.639592,0.060955,19.310900
484056,3873073,41599,58837.089329,322.401108,-10.375126,0.779347,-0.622267,0.073496,19.678900
484057,3873086,41599,58837.089329,322.730497,-11.238179,0.780537,-0.622464,0.057455,18.056499
484058,3901617,41599,58840.095289,323.123836,-11.600120,0.783596,-0.619309,0.049338,13.865100

In [34]:
ztf_elt.to_hdf(file_path, key='ztf_elt', mode='w')

In [39]:
file_paths = glob.glob('../data/ztf_elt/ztf_elt_*.h5')

In [47]:
for file_path in tqdm(file_paths):
    ztf_elt = pd.read_hdf(file_path)
    loc = ztf_elt.columns.get_loc('uz')+1
    mag_app = ztf.mag_app.loc[ztf_elt.ztf_id].values
    if 'mag_app' not in ztf_elt.columns:
        ztf_elt.insert(loc=loc, column='mag_app', value=mag_app)
    else:
        ztf_elt['mag_app'] = mag_app
    ztf_elt.to_hdf(file_path, key='ztf_elt', mode='w')

HBox(children=(FloatProgress(value=0.0, max=3432.0), HTML(value='')))

KeyboardInterrupt:

In [46]:
ztf_elt[cols]

,ztf_id,element_id,mjd,ra,dec,ux,uy,uz,mag_app
0,25248,733,58365.130486,269.830331,-14.496884,-0.002867,-0.987841,0.155440,16.502001
1,37580,733,58372.126366,271.256633,-11.466062,0.021493,-0.978028,0.207361,16.531000
2,37581,733,58371.209190,271.256646,-11.466037,0.021493,-0.978028,0.207361,19.719700
3,37582,733,58371.122523,271.256648,-11.466060,0.021493,-0.978028,0.207361,16.682301
4,37587,733,58321.274572,271.256647,-11.466069,0.021493,-0.978028,0.207361,17.220699
...,...,...,...,...,...,...,...,...,...
1233686,5651378,324582,58904.185752,42.122572,29.195466,0.647485,0.731228,0.214636,18.337299
1233687,5651434,324582,58904.185313,43.256211,29.954124,0.631015,0.743348,0.221933,19.257601
1233688,5651513,324582,58904.185752,42.388038,28.228923,0.650751,0.733102,0.197698,19.199400
1233689,5651704,324582,58904.185752,41.916630,28.631276,0.653128,0.728579,0.206390,18.967100
1233690,5651867,324582,58904.185752,41.868105,28.422819,0.654918,0.727863,0.203216,18.203100